// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: updatefx.proto

package updatefx;

public final class UFXProtocol {
  private UFXProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string urls = 1;
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    java.util.List<java.lang.String>
    getUrlsList();
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    int getUrlsCount();
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    java.lang.String getUrls(int index);
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    com.google.protobuf.ByteString
        getUrlsBytes(int index);

    // required bytes hash = 2;
    /**
     * <code>required bytes hash = 2;</code>
     *
     * <pre>
     * SHA256
     * </pre>
     */
    boolean hasHash();
    /**
     * <code>required bytes hash = 2;</code>
     *
     * <pre>
     * SHA256
     * </pre>
     */
    com.google.protobuf.ByteString getHash();

    // required uint32 version = 3;
    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * Monotonically increasing integer for which higher versions are newer.
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * Monotonically increasing integer for which higher versions are newer.
     * </pre>
     */
    int getVersion();

    // required uint32 patch_size = 4;
    /**
     * <code>required uint32 patch_size = 4;</code>
     *
     * <pre>
     * Size in bytes of the file pointed to by URLs.
     * </pre>
     */
    boolean hasPatchSize();
    /**
     * <code>required uint32 patch_size = 4;</code>
     *
     * <pre>
     * Size in bytes of the file pointed to by URLs.
     * </pre>
     */
    int getPatchSize();
  }
  /**
   * Protobuf type {@code updatefx.Update}
   */
  public static final class Update extends
      com.google.protobuf.GeneratedMessage
      implements UpdateOrBuilder {
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Update(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Update defaultInstance;
    public static Update getDefaultInstance() {
      return defaultInstance;
    }

    public Update getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Update(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                urls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              urls_.add(input.readBytes());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              hash_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              version_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              patchSize_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          urls_ = new com.google.protobuf.UnmodifiableLazyStringList(urls_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return updatefx.UFXProtocol.internal_static_updatefx_Update_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return updatefx.UFXProtocol.internal_static_updatefx_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              updatefx.UFXProtocol.Update.class, updatefx.UFXProtocol.Update.Builder.class);
    }

    public static com.google.protobuf.Parser<Update> PARSER =
        new com.google.protobuf.AbstractParser<Update>() {
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Update(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated string urls = 1;
    public static final int URLS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList urls_;
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    public java.util.List<java.lang.String>
        getUrlsList() {
      return urls_;
    }
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    public int getUrlsCount() {
      return urls_.size();
    }
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    public java.lang.String getUrls(int index) {
      return urls_.get(index);
    }
    /**
     * <code>repeated string urls = 1;</code>
     *
     * <pre>
     * All URLs for this update are considered to be equivalent. One will be chosen at random.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUrlsBytes(int index) {
      return urls_.getByteString(index);
    }

    // required bytes hash = 2;
    public static final int HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>required bytes hash = 2;</code>
     *
     * <pre>
     * SHA256
     * </pre>
     */
    public boolean hasHash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes hash = 2;</code>
     *
     * <pre>
     * SHA256
     * </pre>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    // required uint32 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * Monotonically increasing integer for which higher versions are newer.
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * Monotonically increasing integer for which higher versions are newer.
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // required uint32 patch_size = 4;
    public static final int PATCH_SIZE_FIELD_NUMBER = 4;
    private int patchSize_;
    /**
     * <code>required uint32 patch_size = 4;</code>
     *
     * <pre>
     * Size in bytes of the file pointed to by URLs.
     * </pre>
     */
    public boolean hasPatchSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 patch_size = 4;</code>
     *
     * <pre>
     * Size in bytes of the file pointed to by URLs.
     * </pre>
     */
    public int getPatchSize() {
      return patchSize_;
    }

    private void initFields() {
      urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      hash_ = com.google.protobuf.ByteString.EMPTY;
      version_ = 0;
      patchSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPatchSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < urls_.size(); i++) {
        output.writeBytes(1, urls_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, hash_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(3, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, patchSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < urls_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(urls_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUrlsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, hash_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, patchSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static updatefx.UFXProtocol.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static updatefx.UFXProtocol.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static updatefx.UFXProtocol.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static updatefx.UFXProtocol.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static updatefx.UFXProtocol.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static updatefx.UFXProtocol.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(updatefx.UFXProtocol.Update prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code updatefx.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements updatefx.UFXProtocol.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return updatefx.UFXProtocol.internal_static_updatefx_Update_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return updatefx.UFXProtocol.internal_static_updatefx_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                updatefx.UFXProtocol.Update.class, updatefx.UFXProtocol.Update.Builder.class);
      }

      // Construct using updatefx.UFXProtocol.Update.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        patchSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return updatefx.UFXProtocol.internal_static_updatefx_Update_descriptor;
      }

      public updatefx.UFXProtocol.Update getDefaultInstanceForType() {
        return updatefx.UFXProtocol.Update.getDefaultInstance();
      }

      public updatefx.UFXProtocol.Update build() {
        updatefx.UFXProtocol.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public updatefx.UFXProtocol.Update buildPartial() {
        updatefx.UFXProtocol.Update result = new updatefx.UFXProtocol.Update(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          urls_ = new com.google.protobuf.UnmodifiableLazyStringList(
              urls_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.urls_ = urls_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.patchSize_ = patchSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof updatefx.UFXProtocol.Update) {
          return mergeFrom((updatefx.UFXProtocol.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(updatefx.UFXProtocol.Update other) {
        if (other == updatefx.UFXProtocol.Update.getDefaultInstance()) return this;
        if (!other.urls_.isEmpty()) {
          if (urls_.isEmpty()) {
            urls_ = other.urls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUrlsIsMutable();
            urls_.addAll(other.urls_);
          }
          onChanged();
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasPatchSize()) {
          setPatchSize(other.getPatchSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHash()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasPatchSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        updatefx.UFXProtocol.Update parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (updatefx.UFXProtocol.Update) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string urls = 1;
      private com.google.protobuf.LazyStringList urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUrlsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          urls_ = new com.google.protobuf.LazyStringArrayList(urls_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public java.util.List<java.lang.String>
          getUrlsList() {
        return java.util.Collections.unmodifiableList(urls_);
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public int getUrlsCount() {
        return urls_.size();
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public java.lang.String getUrls(int index) {
        return urls_.get(index);
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUrlsBytes(int index) {
        return urls_.getByteString(index);
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public Builder setUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public Builder addUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public Builder addAllUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureUrlsIsMutable();
        super.addAll(values, urls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public Builder clearUrls() {
        urls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 1;</code>
       *
       * <pre>
       * All URLs for this update are considered to be equivalent. One will be chosen at random.
       * </pre>
       */
      public Builder addUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.add(value);
        onChanged();
        return this;
      }

      // required bytes hash = 2;
      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes hash = 2;</code>
       *
       * <pre>
       * SHA256
       * </pre>
       */
      public boolean hasHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes hash = 2;</code>
       *
       * <pre>
       * SHA256
       * </pre>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>required bytes hash = 2;</code>
       *
       * <pre>
       * SHA256
       * </pre>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes hash = 2;</code>
       *
       * <pre>
       * SHA256
       * </pre>
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      // required uint32 version = 3;
      private int version_ ;
      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * Monotonically increasing integer for which higher versions are newer.
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * Monotonically increasing integer for which higher versions are newer.
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * Monotonically increasing integer for which higher versions are newer.
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * Monotonically increasing integer for which higher versions are newer.
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      // required uint32 patch_size = 4;
      private int patchSize_ ;
      /**
       * <code>required uint32 patch_size = 4;</code>
       *
       * <pre>
       * Size in bytes of the file pointed to by URLs.
       * </pre>
       */
      public boolean hasPatchSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 patch_size = 4;</code>
       *
       * <pre>
       * Size in bytes of the file pointed to by URLs.
       * </pre>
       */
      public int getPatchSize() {
        return patchSize_;
      }
      /**
       * <code>required uint32 patch_size = 4;</code>
       *
       * <pre>
       * Size in bytes of the file pointed to by URLs.
       * </pre>
       */
      public Builder setPatchSize(int value) {
        bitField0_ |= 0x00000008;
        patchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 patch_size = 4;</code>
       *
       * <pre>
       * Size in bytes of the file pointed to by URLs.
       * </pre>
       */
      public Builder clearPatchSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        patchSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:updatefx.Update)
    }

    static {
      defaultInstance = new Update(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:updatefx.Update)
  }

  public interface UpdatesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .updatefx.Update updates = 1;
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    java.util.List<updatefx.UFXProtocol.Update> 
        getUpdatesList();
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    updatefx.UFXProtocol.Update getUpdates(int index);
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    int getUpdatesCount();
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    java.util.List<? extends updatefx.UFXProtocol.UpdateOrBuilder> 
        getUpdatesOrBuilderList();
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    updatefx.UFXProtocol.UpdateOrBuilder getUpdatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code updatefx.Updates}
   */
  public static final class Updates extends
      com.google.protobuf.GeneratedMessage
      implements UpdatesOrBuilder {
    // Use Updates.newBuilder() to construct.
    private Updates(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Updates(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Updates defaultInstance;
    public static Updates getDefaultInstance() {
      return defaultInstance;
    }

    public Updates getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Updates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                updates_ = new java.util.ArrayList<updatefx.UFXProtocol.Update>();
                mutable_bitField0_ |= 0x00000001;
              }
              updates_.add(input.readMessage(updatefx.UFXProtocol.Update.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = java.util.Collections.unmodifiableList(updates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return updatefx.UFXProtocol.internal_static_updatefx_Updates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return updatefx.UFXProtocol.internal_static_updatefx_Updates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              updatefx.UFXProtocol.Updates.class, updatefx.UFXProtocol.Updates.Builder.class);
    }

    public static com.google.protobuf.Parser<Updates> PARSER =
        new com.google.protobuf.AbstractParser<Updates>() {
      public Updates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Updates(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Updates> getParserForType() {
      return PARSER;
    }

    // repeated .updatefx.Update updates = 1;
    public static final int UPDATES_FIELD_NUMBER = 1;
    private java.util.List<updatefx.UFXProtocol.Update> updates_;
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    public java.util.List<updatefx.UFXProtocol.Update> getUpdatesList() {
      return updates_;
    }
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    public java.util.List<? extends updatefx.UFXProtocol.UpdateOrBuilder> 
        getUpdatesOrBuilderList() {
      return updates_;
    }
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    public int getUpdatesCount() {
      return updates_.size();
    }
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    public updatefx.UFXProtocol.Update getUpdates(int index) {
      return updates_.get(index);
    }
    /**
     * <code>repeated .updatefx.Update updates = 1;</code>
     */
    public updatefx.UFXProtocol.UpdateOrBuilder getUpdatesOrBuilder(
        int index) {
      return updates_.get(index);
    }

    private void initFields() {
      updates_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getUpdatesCount(); i++) {
        if (!getUpdates(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < updates_.size(); i++) {
        output.writeMessage(1, updates_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < updates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, updates_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static updatefx.UFXProtocol.Updates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Updates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static updatefx.UFXProtocol.Updates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static updatefx.UFXProtocol.Updates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(updatefx.UFXProtocol.Updates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code updatefx.Updates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements updatefx.UFXProtocol.UpdatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return updatefx.UFXProtocol.internal_static_updatefx_Updates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return updatefx.UFXProtocol.internal_static_updatefx_Updates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                updatefx.UFXProtocol.Updates.class, updatefx.UFXProtocol.Updates.Builder.class);
      }

      // Construct using updatefx.UFXProtocol.Updates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdatesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return updatefx.UFXProtocol.internal_static_updatefx_Updates_descriptor;
      }

      public updatefx.UFXProtocol.Updates getDefaultInstanceForType() {
        return updatefx.UFXProtocol.Updates.getDefaultInstance();
      }

      public updatefx.UFXProtocol.Updates build() {
        updatefx.UFXProtocol.Updates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public updatefx.UFXProtocol.Updates buildPartial() {
        updatefx.UFXProtocol.Updates result = new updatefx.UFXProtocol.Updates(this);
        int from_bitField0_ = bitField0_;
        if (updatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            updates_ = java.util.Collections.unmodifiableList(updates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.updates_ = updates_;
        } else {
          result.updates_ = updatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof updatefx.UFXProtocol.Updates) {
          return mergeFrom((updatefx.UFXProtocol.Updates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(updatefx.UFXProtocol.Updates other) {
        if (other == updatefx.UFXProtocol.Updates.getDefaultInstance()) return this;
        if (updatesBuilder_ == null) {
          if (!other.updates_.isEmpty()) {
            if (updates_.isEmpty()) {
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUpdatesIsMutable();
              updates_.addAll(other.updates_);
            }
            onChanged();
          }
        } else {
          if (!other.updates_.isEmpty()) {
            if (updatesBuilder_.isEmpty()) {
              updatesBuilder_.dispose();
              updatesBuilder_ = null;
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              updatesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUpdatesFieldBuilder() : null;
            } else {
              updatesBuilder_.addAllMessages(other.updates_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUpdatesCount(); i++) {
          if (!getUpdates(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        updatefx.UFXProtocol.Updates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (updatefx.UFXProtocol.Updates) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .updatefx.Update updates = 1;
      private java.util.List<updatefx.UFXProtocol.Update> updates_ =
        java.util.Collections.emptyList();
      private void ensureUpdatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = new java.util.ArrayList<updatefx.UFXProtocol.Update>(updates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          updatefx.UFXProtocol.Update, updatefx.UFXProtocol.Update.Builder, updatefx.UFXProtocol.UpdateOrBuilder> updatesBuilder_;

      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public java.util.List<updatefx.UFXProtocol.Update> getUpdatesList() {
        if (updatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updates_);
        } else {
          return updatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public int getUpdatesCount() {
        if (updatesBuilder_ == null) {
          return updates_.size();
        } else {
          return updatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public updatefx.UFXProtocol.Update getUpdates(int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);
        } else {
          return updatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder setUpdates(
          int index, updatefx.UFXProtocol.Update value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.set(index, value);
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder setUpdates(
          int index, updatefx.UFXProtocol.Update.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.set(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder addUpdates(updatefx.UFXProtocol.Update value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder addUpdates(
          int index, updatefx.UFXProtocol.Update value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(index, value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder addUpdates(
          updatefx.UFXProtocol.Update.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder addUpdates(
          int index, updatefx.UFXProtocol.Update.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder addAllUpdates(
          java.lang.Iterable<? extends updatefx.UFXProtocol.Update> values) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          super.addAll(values, updates_);
          onChanged();
        } else {
          updatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder clearUpdates() {
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public Builder removeUpdates(int index) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.remove(index);
          onChanged();
        } else {
          updatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public updatefx.UFXProtocol.Update.Builder getUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public updatefx.UFXProtocol.UpdateOrBuilder getUpdatesOrBuilder(
          int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);  } else {
          return updatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public java.util.List<? extends updatefx.UFXProtocol.UpdateOrBuilder> 
           getUpdatesOrBuilderList() {
        if (updatesBuilder_ != null) {
          return updatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updates_);
        }
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public updatefx.UFXProtocol.Update.Builder addUpdatesBuilder() {
        return getUpdatesFieldBuilder().addBuilder(
            updatefx.UFXProtocol.Update.getDefaultInstance());
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public updatefx.UFXProtocol.Update.Builder addUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().addBuilder(
            index, updatefx.UFXProtocol.Update.getDefaultInstance());
      }
      /**
       * <code>repeated .updatefx.Update updates = 1;</code>
       */
      public java.util.List<updatefx.UFXProtocol.Update.Builder> 
           getUpdatesBuilderList() {
        return getUpdatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          updatefx.UFXProtocol.Update, updatefx.UFXProtocol.Update.Builder, updatefx.UFXProtocol.UpdateOrBuilder> 
          getUpdatesFieldBuilder() {
        if (updatesBuilder_ == null) {
          updatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              updatefx.UFXProtocol.Update, updatefx.UFXProtocol.Update.Builder, updatefx.UFXProtocol.UpdateOrBuilder>(
                  updates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          updates_ = null;
        }
        return updatesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:updatefx.Updates)
    }

    static {
      defaultInstance = new Updates(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:updatefx.Updates)
  }

  public interface SignedUpdatesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes updates = 1;
    /**
     * <code>required bytes updates = 1;</code>
     *
     * <pre>
     * Serialized Updates message.
     * </pre>
     */
    boolean hasUpdates();
    /**
     * <code>required bytes updates = 1;</code>
     *
     * <pre>
     * Serialized Updates message.
     * </pre>
     */
    com.google.protobuf.ByteString getUpdates();

    // repeated string signatures = 2;
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    java.util.List<java.lang.String>
    getSignaturesList();
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    int getSignaturesCount();
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    java.lang.String getSignatures(int index);
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    com.google.protobuf.ByteString
        getSignaturesBytes(int index);
  }
  /**
   * Protobuf type {@code updatefx.SignedUpdates}
   */
  public static final class SignedUpdates extends
      com.google.protobuf.GeneratedMessage
      implements SignedUpdatesOrBuilder {
    // Use SignedUpdates.newBuilder() to construct.
    private SignedUpdates(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SignedUpdates(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SignedUpdates defaultInstance;
    public static SignedUpdates getDefaultInstance() {
      return defaultInstance;
    }

    public SignedUpdates getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SignedUpdates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              updates_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                signatures_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              signatures_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          signatures_ = new com.google.protobuf.UnmodifiableLazyStringList(signatures_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return updatefx.UFXProtocol.internal_static_updatefx_SignedUpdates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return updatefx.UFXProtocol.internal_static_updatefx_SignedUpdates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              updatefx.UFXProtocol.SignedUpdates.class, updatefx.UFXProtocol.SignedUpdates.Builder.class);
    }

    public static com.google.protobuf.Parser<SignedUpdates> PARSER =
        new com.google.protobuf.AbstractParser<SignedUpdates>() {
      public SignedUpdates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignedUpdates(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SignedUpdates> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes updates = 1;
    public static final int UPDATES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString updates_;
    /**
     * <code>required bytes updates = 1;</code>
     *
     * <pre>
     * Serialized Updates message.
     * </pre>
     */
    public boolean hasUpdates() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes updates = 1;</code>
     *
     * <pre>
     * Serialized Updates message.
     * </pre>
     */
    public com.google.protobuf.ByteString getUpdates() {
      return updates_;
    }

    // repeated string signatures = 2;
    public static final int SIGNATURES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList signatures_;
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    public java.util.List<java.lang.String>
        getSignaturesList() {
      return signatures_;
    }
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    public int getSignaturesCount() {
      return signatures_.size();
    }
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    public java.lang.String getSignatures(int index) {
      return signatures_.get(index);
    }
    /**
     * <code>repeated string signatures = 2;</code>
     *
     * <pre>
     * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
     * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
     * coded) threshold.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSignaturesBytes(int index) {
      return signatures_.getByteString(index);
    }

    private void initFields() {
      updates_ = com.google.protobuf.ByteString.EMPTY;
      signatures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUpdates()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, updates_);
      }
      for (int i = 0; i < signatures_.size(); i++) {
        output.writeBytes(2, signatures_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, updates_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < signatures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(signatures_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSignaturesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static updatefx.UFXProtocol.SignedUpdates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static updatefx.UFXProtocol.SignedUpdates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(updatefx.UFXProtocol.SignedUpdates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code updatefx.SignedUpdates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements updatefx.UFXProtocol.SignedUpdatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return updatefx.UFXProtocol.internal_static_updatefx_SignedUpdates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return updatefx.UFXProtocol.internal_static_updatefx_SignedUpdates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                updatefx.UFXProtocol.SignedUpdates.class, updatefx.UFXProtocol.SignedUpdates.Builder.class);
      }

      // Construct using updatefx.UFXProtocol.SignedUpdates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        updates_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signatures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return updatefx.UFXProtocol.internal_static_updatefx_SignedUpdates_descriptor;
      }

      public updatefx.UFXProtocol.SignedUpdates getDefaultInstanceForType() {
        return updatefx.UFXProtocol.SignedUpdates.getDefaultInstance();
      }

      public updatefx.UFXProtocol.SignedUpdates build() {
        updatefx.UFXProtocol.SignedUpdates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public updatefx.UFXProtocol.SignedUpdates buildPartial() {
        updatefx.UFXProtocol.SignedUpdates result = new updatefx.UFXProtocol.SignedUpdates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.updates_ = updates_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          signatures_ = new com.google.protobuf.UnmodifiableLazyStringList(
              signatures_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.signatures_ = signatures_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof updatefx.UFXProtocol.SignedUpdates) {
          return mergeFrom((updatefx.UFXProtocol.SignedUpdates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(updatefx.UFXProtocol.SignedUpdates other) {
        if (other == updatefx.UFXProtocol.SignedUpdates.getDefaultInstance()) return this;
        if (other.hasUpdates()) {
          setUpdates(other.getUpdates());
        }
        if (!other.signatures_.isEmpty()) {
          if (signatures_.isEmpty()) {
            signatures_ = other.signatures_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSignaturesIsMutable();
            signatures_.addAll(other.signatures_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUpdates()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        updatefx.UFXProtocol.SignedUpdates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (updatefx.UFXProtocol.SignedUpdates) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes updates = 1;
      private com.google.protobuf.ByteString updates_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes updates = 1;</code>
       *
       * <pre>
       * Serialized Updates message.
       * </pre>
       */
      public boolean hasUpdates() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes updates = 1;</code>
       *
       * <pre>
       * Serialized Updates message.
       * </pre>
       */
      public com.google.protobuf.ByteString getUpdates() {
        return updates_;
      }
      /**
       * <code>required bytes updates = 1;</code>
       *
       * <pre>
       * Serialized Updates message.
       * </pre>
       */
      public Builder setUpdates(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        updates_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes updates = 1;</code>
       *
       * <pre>
       * Serialized Updates message.
       * </pre>
       */
      public Builder clearUpdates() {
        bitField0_ = (bitField0_ & ~0x00000001);
        updates_ = getDefaultInstance().getUpdates();
        onChanged();
        return this;
      }

      // repeated string signatures = 2;
      private com.google.protobuf.LazyStringList signatures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          signatures_ = new com.google.protobuf.LazyStringArrayList(signatures_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public java.util.List<java.lang.String>
          getSignaturesList() {
        return java.util.Collections.unmodifiableList(signatures_);
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public int getSignaturesCount() {
        return signatures_.size();
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public java.lang.String getSignatures(int index) {
        return signatures_.get(index);
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSignaturesBytes(int index) {
        return signatures_.getByteString(index);
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public Builder setSignatures(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public Builder addSignatures(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public Builder addAllSignatures(
          java.lang.Iterable<java.lang.String> values) {
        ensureSignaturesIsMutable();
        super.addAll(values, signatures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public Builder clearSignatures() {
        signatures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signatures = 2;</code>
       *
       * <pre>
       * Bitcoin-style message signatures where the message is SHA256(updates) in textual form. The recovered keys
       * are checked against the hard-coded list of allowed signers and there must be sufficient to reach the (hard
       * coded) threshold.
       * </pre>
       */
      public Builder addSignaturesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:updatefx.SignedUpdates)
    }

    static {
      defaultInstance = new SignedUpdates(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:updatefx.SignedUpdates)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_updatefx_Update_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_updatefx_Update_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_updatefx_Updates_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_updatefx_Updates_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_updatefx_SignedUpdates_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_updatefx_SignedUpdates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016updatefx.proto\022\010updatefx\"I\n\006Update\022\014\n\004" +
      "urls\030\001 \003(\t\022\014\n\004hash\030\002 \002(\014\022\017\n\007version\030\003 \002(" +
      "\r\022\022\n\npatch_size\030\004 \002(\r\",\n\007Updates\022!\n\007upda" +
      "tes\030\001 \003(\0132\020.updatefx.Update\"4\n\rSignedUpd" +
      "ates\022\017\n\007updates\030\001 \002(\014\022\022\n\nsignatures\030\002 \003(" +
      "\tB\027\n\010updatefxB\013UFXProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_updatefx_Update_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_updatefx_Update_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_updatefx_Update_descriptor,
              new java.lang.String[] { "Urls", "Hash", "Version", "PatchSize", });
          internal_static_updatefx_Updates_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_updatefx_Updates_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_updatefx_Updates_descriptor,
              new java.lang.String[] { "Updates", });
          internal_static_updatefx_SignedUpdates_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_updatefx_SignedUpdates_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_updatefx_SignedUpdates_descriptor,
              new java.lang.String[] { "Updates", "Signatures", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
